# Generated by Django 5.2.11 on 2026-02-13 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('agencia', models.CharField(default='0001', max_length=4)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('limite', models.DecimalField(decimal_places=2, default=500.0, max_digits=15)),
                ('limite_saques', models.IntegerField(default=3)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Depósito'), ('S', 'Saque')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='contas.conta')),
            ],
        ),
    ]
