# Generated by Django 5.2.11 on 2026-02-25 00:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='conta',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='conta',
            name='limite',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='conta',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('DEPOSITO', 'Depósito'), ('SAQUE', 'Saque')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddField(
            model_name='conta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='contas.cliente'),
            preserve_default=False,
        ),
    ]
